[build]
  # Commande de build pour React/Vite
  command = "npm run build"
  
  # Dossier de publication (où se trouvent les fichiers buildés)
  publish = "dist"

[build.environment]
  # Version Node.js
  NODE_VERSION = "18"
  
  # Désactiver Python
  PYTHON_VERSION = ""

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"